CREATE TYPE public.user_type AS ENUM (
    'ADMIN',
    'USER'
);

CREATE TABLE IF NOT EXISTS public.users (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name CHARACTER VARYING(50)  NOT NULL,
    email CHARACTER VARYING(50)  NOT NULL,
    image_url TEXT DEFAULT NULL,
    type public.user_type NOT NULL DEFAULT 'USER',
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
) WITHOUT OIDS;