version: 2
updates:
  - package-ecosystem: npm # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
  - muhamedfazeel
  - dev-fazeel
